Add make to Dockerfile
HERMES-SOC/hermes_instrument pull request #13
Opened 2022-04-08 17:11 UTC by tonyastrofig

Adding the apt-get update and install make to the Dockerfile

2022-04-08 18:16 UTC, tonyastrofig commented
@ehsteve, I created an issue:
https://github.com/HERMES-SOC/hermes_instrument/issues/12
and then created a branch named "add_make".  I only modified 1 file, the dockerfile.  I checked that the container built and was able to make the Sphinx documentation.  All checks have passed.  So I think it is ready for your review.

2022-04-08 19:33 UTC, ehsteve commented on .devcontainer/Dockerfile
> +RUN apt-get update && \
why run update again? i Would just add it the list of commands in the run command above

2022-04-08 19:35 UTC, ehsteve requested changes
This does add the make command but it adds an unnecessary update command.

2022-04-12 00:12 UTC, ehsteve approved these changes

2022-04-18 14:59 UTC, tonyastrofig commented on .devcontainer/Dockerfile
> +    apt-get install make && \
Correctly installs make for sphinx documentation

2022-04-18 14:59 UTC, tonyastrofig commented on docs/Makefile
> +clean:
make clean successfully removes __build directory

2022-04-18 15:02 UTC, tonyastrofig commented
@ehsteve, your changes all look good, but since I generated the pull request I can't approve it.  Once you re-approve it, do I hit the "Merge pull request" button?

2022-04-18 15:33 UTC, ehsteve approved these changes

2022-04-18 15:34 UTC, merged